server:
  port: 8010

#mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml

spring:
  application:
    name: micro-auth
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/micro?userUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
  security:
    user:
      name: admin
      password: 123456

  # Redis
  redis:
    password: 123456
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: micro-auth

jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: 8c74d7c924494b2b94a216785e7f47ac #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24*7)

redisson:
  address: redis://127.0.0.1:6379

