server:
  port: 8030

spring:
  application:
    name: micro-search
  security:
    user:
      name: admin
      password: 123456
  data:
    elasticsearch:
      repositories:
        enabled: true
  elasticsearch:
    rest:
      uris: localhost:9200

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: micro-search

jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: 8c74d7c924494b2b94a216785e7f47ac #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24*7)



